### ISSUE TITLE
Error in psnr function

### ISSUE THREAD

**Issue by Linuxuser4** [DevKiHyun/SRCNN-Tensorflow#2]
I am getting the following error. Should I convert to numpy array or something to solve? 
I have python 3.5.6 version in anaconda environment

Traceback (most recent call last):
  File "main.py", line 20, in <module>
    train.training(SRCNN, args)
  File "../SRCNN/train.py", line 43, in training
    _psnr = psnr(test_labels[i], test_inputs[i], peak=1)
  File "../SRCNN/util.py", line 182, in psnr
    x = x.astype(np.float32)
AttributeError: 'int' object has no attribute 'astype'

**Comment by DevKiHyun** [comment]
def psnr(x, y, peak=255):
    '''
    :param x: images
    :param y: another images
    :param peak: MAX_i peak. if int8 -> peak =255
    :return: return psnr value
    '''
    _max = peak
    x = x.astype(np.float32)
    y = y.astype(np.float32)
    diff = (x-y).flatten('C')

    rmse = np.sqrt(np.mean(diff**2))
    result = 20 * np.log10(_max/rmse)
    return result

This is custom psnr calculate function. And x,y are image data. If your images were correctly imported by 'cv2' or any image library, then x,y almost be array of 'numpy' type and their shape must be [height, width, n_channel]. I think that the error occurs because x and y are not of type numpy. First, you should check that x, y type is numpy array and that their shape is (height, width, n_channel)!

(Guess) 
Maybe you don't import image. ex) wrong path, have no images, ...
So, you should import image correctly.

Finally, if your method does not work, I suggest you follow my overall approach first. Please refer to the readme.

**Comment by Linuxuser4** [comment]
Thanks for the guidance. There were 2 changes I made. I had to replace the backward slashes with forward for use in linux-octave. Also, I downgraded from 3.6 to 3.5. With these, I can am able to run the code.
